### Read file

In [ ]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv("movies_info.csv")

# Display the first 5 rows
df

,original_title,overview,genres
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"['Drama', 'Crime']"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","['Drama', 'Crime']"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"['Drama', 'Crime']"
3,Schindler's List,The true story of how businessman Oskar Schind...,"['Drama', 'History', 'War']"
4,12 Angry Men,The defense and the prosecution have rested an...,['Drama']
...,...,...,...
9995,Elektra,Elektra the warrior survives a near-death expe...,"['Action', 'Fantasy', 'Adventure']"
9996,Les Trois Frères : Le Retour,Three brothers are reunited on the occasion of...,['Comedy']
9997,Защитники,"During the Cold War, an organization called ""P...","['Science Fiction', 'Action', 'Fantasy', 'Come..."
9998,Winnie the Pooh: Blood and Honey,After Christopher Robin abandons them for coll...,"['Horror', 'Thriller']"
9999,The Little Mermaid,A young reporter and his niece discover a beau...,"['Family', 'Adventure', 'Fantasy', 'Romance', ..."

### Create a copy

In [ ]:
df_movies_info = df.copy()
df_movies_info

,original_title,overview,genres
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"['Drama', 'Crime']"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","['Drama', 'Crime']"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"['Drama', 'Crime']"
3,Schindler's List,The true story of how businessman Oskar Schind...,"['Drama', 'History', 'War']"
4,12 Angry Men,The defense and the prosecution have rested an...,['Drama']
...,...,...,...
9995,Elektra,Elektra the warrior survives a near-death expe...,"['Action', 'Fantasy', 'Adventure']"
9996,Les Trois Frères : Le Retour,Three brothers are reunited on the occasion of...,['Comedy']
9997,Защитники,"During the Cold War, an organization called ""P...","['Science Fiction', 'Action', 'Fantasy', 'Come..."
9998,Winnie the Pooh: Blood and Honey,After Christopher Robin abandons them for coll...,"['Horror', 'Thriller']"
9999,The Little Mermaid,A young reporter and his niece discover a beau...,"['Family', 'Adventure', 'Fantasy', 'Romance', ..."

In [ ]:
# put all text preprocessing steps into a function to better organize our code
def lower_replace(series):
    output = series.str.lower()
    output = output.str.replace(r'\[.*?\]', '', regex=True) # remove words in brackets
    output = output.str.replace(r'[^\w\s]', '', regex=True) # remove punctuation
    return output

In [ ]:
lower_replace(df_movies_info["overview"])

0       imprisoned in the 1940s for the double murder ...
1       spanning the years 1945 to 1955 a chronicle of...
2       in the continuing saga of the corleone crime f...
3       the true story of how businessman oskar schind...
4       the defense and the prosecution have rested an...
                              ...
9995    elektra the warrior survives a neardeath exper...
9996    three brothers are reunited on the occasion of...
9997    during the cold war an organization called pat...
9998    after christopher robin abandons them for coll...
9999    a young reporter and his niece discover a beau...
Name: overview, Length: 10000, dtype: object

In [ ]:
df_movies_info_cleaned = lower_replace(df_movies_info["overview"])
df_movies_info_cleaned

0       imprisoned in the 1940s for the double murder ...
1       spanning the years 1945 to 1955 a chronicle of...
2       in the continuing saga of the corleone crime f...
3       the true story of how businessman oskar schind...
4       the defense and the prosecution have rested an...
                              ...
9995    elektra the warrior survives a neardeath exper...
9996    three brothers are reunited on the occasion of...
9997    during the cold war an organization called pat...
9998    after christopher robin abandons them for coll...
9999    a young reporter and his niece discover a beau...
Name: overview, Length: 10000, dtype: object

In [ ]:
import spacy ## load the spacy english model
nlp = spacy.load('en_core_web_sm')

In [ ]:
def token_lemma_nonstop(text):
    doc = nlp(text)
    output = [token.lemma_ for token in doc if not token.is_stop]
    output = ' '.join(output)
    return output

In [ ]:
def filter_pos(text, pos_list=['NOUN', 'PROPN']):
    doc = nlp(text)
    output = [(token.text) for token in doc if token.pos_ in pos_list]
    output = ' '.join(output)
    return output

In [ ]:
df_movies_info_cleaned.fillna("").apply(token_lemma_nonstop)

0       imprison 1940 double murder wife lover upstand...
1       span year 1945 1955 chronicle fictional italia...
2       continue saga corleone crime family young vito...
3       true story businessman oskar schindler save th...
4       defense prosecution rest jury file jury room d...
                              ...
9995    elektra warrior survive neardeath experience a...
9996    brother reunite occasion death mother difficul...
9997    cold war organization call patriot create supe...
9998    christopher robin abandon college pooh piglet ...
9999    young reporter niece discover beautiful enchan...
Name: overview, Length: 10000, dtype: object

In [ ]:
text_clean = df_movies_info_cleaned.fillna("").apply(token_lemma_nonstop).apply(filter_pos)

In [ ]:
text_clean

0       imprison murder wife lover upstande banker and...
1       span year chronicle italianamerican corleone c...
2       saga corleone crime family young vito corleone...
3       story businessman oskar schindler life work sl...
4       defense prosecution rest jury file jury room m...
                              ...
9995    elektra warrior experience assassinforhire tar...
9996    brother reunite occasion death mother stage li...
9997    war organization call patriot superhero squad ...
9998    christopher robin abandon college pooh piglet ...
9999                              reporter niece creature
Name: overview, Length: 10000, dtype: object

### Create an NLP pipeline

In [ ]:
# copy down the helper functions
def lower_replace(series):
    output = series.str.lower()
    output = output.str.replace(r'\[.*?\]', '', regex=True)
    output = output.str.replace(r'[^\w\s]', '', regex=True)
    return output

def token_lemma_nonstop(text):
    doc = nlp(text)
    output = [token.lemma_ for token in doc if not token.is_stop]
    output = ' '.join(output)
    return output

def filter_pos(text, pos_list=['NOUN', 'PROPN']):
    doc = nlp(text)
    output = [(token.text) for token in doc if token.pos_ in pos_list]
    output = ' '.join(output)
    return output

In [ ]:
# create an nlp pipeline
def nlp_pipeline(series):
    output = lower_replace(series)
    output = output.apply(token_lemma_nonstop)
    output = output.apply(filter_pos)
    return output

In [ ]:
#test out the pipeline
# view the cleaned, normalized and filtered test sentences
# To replace missing value with string by using fillna
test_clean = nlp_pipeline(df_movies_info["overview"].fillna(""))

In [ ]:
test_clean.head(10)

0    imprison murder wife lover upstande banker and...
1    span year chronicle italianamerican corleone c...
2    saga corleone crime family young vito corleone...
3    story businessman oskar schindler life work sl...
4    defense prosecution rest jury file jury room m...
5    girl chihiro world spirit parent transformatio...
6    batman stake war crime help jim gordon distric...
7    raj generation nri simran daughter chaudhary b...
8    tale death row prison giant john coffey power ...
9    kitaek family interest park livelihood entangl...
Name: overview, dtype: object

In [ ]:
import pandas as pd

df_clean = pd.read_pickle("text_clean.pkl")
df_clean

0       imprison murder wife lover upstande banker and...
1       span year chronicle italianamerican corleone c...
2       saga corleone crime family young vito corleone...
3       story businessman oskar schindler life work sl...
4       defense prosecution rest jury file jury room m...
                              ...
9995    elektra warrior experience assassinforhire tar...
9996    brother reunite occasion death mother stage li...
9997    war organization call patriot superhero squad ...
9998    christopher robin abandon college pooh piglet ...
9999                              reporter niece creature
Name: overview, Length: 10000, dtype: object

###Preprocessing genres with MultiLabelBinarizer
###Vectorizing overviews with TF-IDF
###Combining features
###Computing cosine similarity on demand
###Returning Top-N similar movies for a given title

In [ ]:
df_clean = df_clean.to_frame()  # converts Series to DataFrame
print(df_clean.columns)

Index(['overview'], dtype='object')

In [ ]:
import pandas as pd
import ast

df_genres = pd.read_csv("movies_info.csv")

# convert string representation of list into actual Python list
df_genres['genres'] = df_genres['genres'].apply(ast.literal_eval)
df_genres

,original_title,overview,genres
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[Drama, Crime]"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[Drama, Crime]"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[Drama, Crime]"
3,Schindler's List,The true story of how businessman Oskar Schind...,"[Drama, History, War]"
4,12 Angry Men,The defense and the prosecution have rested an...,[Drama]
...,...,...,...
9995,Elektra,Elektra the warrior survives a near-death expe...,"[Action, Fantasy, Adventure]"
9996,Les Trois Frères : Le Retour,Three brothers are reunited on the occasion of...,[Comedy]
9997,Защитники,"During the Cold War, an organization called ""P...","[Science Fiction, Action, Fantasy, Comedy, Thr..."
9998,Winnie the Pooh: Blood and Honey,After Christopher Robin abandons them for coll...,"[Horror, Thriller]"
9999,The Little Mermaid,A young reporter and his niece discover a beau...,"[Family, Adventure, Fantasy, Romance, Drama]"

In [ ]:
import pandas as pd
import ast
from sklearn.preprocessing import MultiLabelBinarizer


# Apply MultiLabelBinarizer
#genres for MultiLabelBinarizer (categorical features).
mlb = MultiLabelBinarizer()
genre_matrix = mlb.fit_transform(df_genres['genres'])

# Create a new DataFrame with binary columns
df_genres = pd.DataFrame(genre_matrix, columns=mlb.classes_, index=df_genres.index)

df_genres

,Action,Adventure,Animation,Comedy,Crime,Drama,Family,Fantasy,History,Horror,Music,Mystery,Romance,Science Fiction,TV Movie,Thriller,War,Western
0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
9996,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9997,1,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0
9998,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0
9999,0,1,0,0,0,1,1,1,0,0,0,0,1,0,0,0,0,0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')
overview_matrix = tfidf.fit_transform(df_clean['overview'])
overview_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 145935 stored elements and shape (10000, 19874)>

###Combine overview + genre features By adding genre encoding:

Drama + Crime movies are pulled closer together
Action + Fantasy movies are pulled closer together

In [ ]:
from scipy.sparse import hstack, csr_matrix

genre_sparse = csr_matrix(df_genres)
combined_features = hstack([overview_matrix, genre_sparse])
combined_features

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 172336 stored elements and shape (10000, 19892)>

###Compute similarity

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(combined_features)

In [ ]:
df1 = pd.read_csv("movies_info.csv")
df1.columns

Index(['original_title', 'overview', 'genres'], dtype='object')

In [ ]:
df1

,original_title,overview,genres
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"['Drama', 'Crime']"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","['Drama', 'Crime']"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"['Drama', 'Crime']"
3,Schindler's List,The true story of how businessman Oskar Schind...,"['Drama', 'History', 'War']"
4,12 Angry Men,The defense and the prosecution have rested an...,['Drama']
...,...,...,...
9995,Elektra,Elektra the warrior survives a near-death expe...,"['Action', 'Fantasy', 'Adventure']"
9996,Les Trois Frères : Le Retour,Three brothers are reunited on the occasion of...,['Comedy']
9997,Защитники,"During the Cold War, an organization called ""P...","['Science Fiction', 'Action', 'Fantasy', 'Come..."
9998,Winnie the Pooh: Blood and Honey,After Christopher Robin abandons them for coll...,"['Horror', 'Thriller']"
9999,The Little Mermaid,A young reporter and his niece discover a beau...,"['Family', 'Adventure', 'Fantasy', 'Romance', ..."

In [ ]:
def recommend_movies(title, df1, similarity_matrix, top_n=10):
    # Find the index of the movie
    idx = df1[df1['original_title'].str.lower() == title.lower()].index
    if len(idx) == 0:
        return f"Movie '{title}' not found in dataset."
    idx = idx[0]

    # Get similarity scores for that movie
    sim_scores = list(enumerate(similarity_matrix[idx]))

    # Sort by similarity score (highest first)
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Exclude the movie itself
    sim_scores = sim_scores[1:top_n+1]

    # Extract indices and scores
    movie_indices = [i[0] for i in sim_scores]
    scores = [i[1] for i in sim_scores]

    # Build result DataFrame with scores
    result = df1[['original_title', 'genres']].iloc[movie_indices].copy()
    result['similarity_score'] = scores

    return result

# Example usage
print(recommend_movies("Blood & Gold", df1, similarity_matrix, top_n=10))

             original_title                      genres  similarity_score
1495                Dunkirk  ['War', 'Action', 'Drama']          0.793577
5583         Hamburger Hill  ['War', 'Action', 'Drama']          0.789856
1393  Letters from Iwo Jima  ['Action', 'Drama', 'War']          0.788270
6205             Сталинград  ['War', 'Action', 'Drama']          0.780478
4113              Civil War  ['War', 'Action', 'Drama']          0.779672
5853            Sand Castle  ['War', 'Action', 'Drama']          0.776780
4724          Memphis Belle  ['Drama', 'War', 'Action']          0.775086
6165          The Kill Team  ['War', 'Action', 'Drama']          0.774138
4762       Forces spéciales  ['Action', 'Drama', 'War']          0.773817
1650              Greyhound  ['War', 'Action', 'Drama']          0.769396

In [ ]:
recommend_movies("The Godfather", df1, similarity_matrix, top_n=10)

,original_title,genres,similarity_score
2,The Godfather Part II,"['Drama', 'Crime']",0.811659
3397,"Extremely Wicked, Shockingly Evil and Vile","['Drama', 'Crime']",0.715475
9575,Rampart,"['Crime', 'Drama']",0.699839
1573,The Unforgivable,"['Drama', 'Crime']",0.698164
1002,Le Clan des Siciliens,"['Crime', 'Drama']",0.694495
3891,Aus dem Nichts,"['Drama', 'Crime']",0.693775
2555,Romanzo criminale,"['Crime', 'Drama']",0.691994
1887,Cherry,"['Drama', 'Crime']",0.691925
1411,Midnight Express,"['Drama', 'Crime']",0.691287
2313,The Public Enemy,"['Crime', 'Drama']",0.690163

###Interactive Features

In [ ]:
movie_input = input("Enter a movie title: ")

# normalize the input to lowercase before passing
results = recommend_movies(movie_input.lower(), df1, similarity_matrix, top_n=10)

if isinstance(results, str):
    print(results)
else:
    print(f"\nTop 10 recommendations for '{movie_input}':\n")
results

Enter a movie title: blood & gold

Top 10 recommendations for 'blood & gold':

             original_title                      genres  similarity_score
1495                Dunkirk  ['War', 'Action', 'Drama']          0.793577
5583         Hamburger Hill  ['War', 'Action', 'Drama']          0.789856
1393  Letters from Iwo Jima  ['Action', 'Drama', 'War']          0.788270
6205             Сталинград  ['War', 'Action', 'Drama']          0.780478
4113              Civil War  ['War', 'Action', 'Drama']          0.779672
5853            Sand Castle  ['War', 'Action', 'Drama']          0.776780
4724          Memphis Belle  ['Drama', 'War', 'Action']          0.775086
6165          The Kill Team  ['War', 'Action', 'Drama']          0.774138
4762       Forces spéciales  ['Action', 'Drama', 'War']          0.773817
1650              Greyhound  ['War', 'Action', 'Drama']          0.769396

###Document Similarity with Embeddings with transformer

###Step 1: Extract Embeddings

In [ ]:
from transformers import pipeline
import pandas as pd

In [ ]:
# modify the column width
pd.set_option('display.max_colwidth', 50)

# read in the movies data
movies = pd.read_csv('movies_info.csv')
movies.head(5)

,original_title,overview,genres
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"['Drama', 'Crime']"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","['Drama', 'Crime']"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"['Drama', 'Crime']"
3,Schindler's List,The true story of how businessman Oskar Schind...,"['Drama', 'History', 'War']"
4,12 Angry Men,The defense and the prosecution have rested an...,['Drama']

###2. Prepare the text columns

In [ ]:
movies["combined_text"] = (
    movies["original_title"].fillna('') + " " +
    movies["overview"].fillna('') + " " +
    movies["genres"].fillna('')
)
movies

,original_title,overview,genres,combined_text
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"['Drama', 'Crime']",The Shawshank Redemption Imprisoned in the 194...
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","['Drama', 'Crime']","The Godfather Spanning the years 1945 to 1955,..."
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"['Drama', 'Crime']",The Godfather Part II In the continuing saga o...
3,Schindler's List,The true story of how businessman Oskar Schind...,"['Drama', 'History', 'War']",Schindler's List The true story of how busines...
4,12 Angry Men,The defense and the prosecution have rested an...,['Drama'],12 Angry Men The defense and the prosecution h...
...,...,...,...,...
9995,Elektra,Elektra the warrior survives a near-death expe...,"['Action', 'Fantasy', 'Adventure']",Elektra Elektra the warrior survives a near-de...
9996,Les Trois Frères : Le Retour,Three brothers are reunited on the occasion of...,['Comedy'],Les Trois Frères : Le Retour Three brothers ar...
9997,Защитники,"During the Cold War, an organization called ""P...","['Science Fiction', 'Action', 'Fantasy', 'Come...","Защитники During the Cold War, an organization..."
9998,Winnie the Pooh: Blood and Honey,After Christopher Robin abandons them for coll...,"['Horror', 'Thriller']",Winnie the Pooh: Blood and Honey After Christo...
9999,The Little Mermaid,A young reporter and his niece discover a beau...,"['Family', 'Adventure', 'Fantasy', 'Romance', ...",The Little Mermaid A young reporter and his ni...

In [ ]:
# Apply pipeline to the combined_text column
movies["combined_text"] = nlp_pipeline(movies["combined_text"])

###3. Load sentence-transformers model

In [ ]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer("all-MiniLM-L6-v2")
#Size: Small (22MB)
#Speed: Very fast, suitable for large datasets
#Accuracy: Strong performance on semantic similarity
#Use case: Great balance of speed and quality for movie recommendations

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

###4. Create embeddings
This converts every movie into a numeric embedding vector.

In [ ]:
embedding_matrix = model.encode(
    movies["combined_text"].tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/313 [00:00<?, ?it/s]

In [ ]:
import os
import numpy as np

if os.path.exists('embedding_matrix.npy'):
    embedding_matrix = np.load('embedding_matrix.npy')
else:
    embedding_matrix = model.encode(movies["combined_text"].tolist(), show_progress_bar=True)
    np.save('embedding_matrix.npy', embedding_matrix)

Batches:   0%|          | 0/313 [00:00<?, ?it/s]

In [ ]:
#To import embeddings for future use without wasting time to run again
import numpy as np

# Load embeddings
embedding_matrix = np.load('embedding_matrix.npy')

# Now you can use embedding_matrix in your recommendation functions

###5. Create recommendation function

In [ ]:
def recommend_movies_2(movie_title, movies, embedding_matrix, top_n=10):
    # case-insensitive title matching
    title_to_index = {title.lower(): idx for idx, title in enumerate(movies["original_title"])}

    if movie_title.lower() not in title_to_index:
        return f"Movie title '{movie_title}' not found in the dataset."

    movie_idx = title_to_index[movie_title.lower()]

    # get embedding of selected movie
    movie_vector = embedding_matrix[movie_idx].reshape(1, -1)

    # compute cosine similarity
    sim_scores = cosine_similarity(movie_vector, embedding_matrix).flatten()

    # exclude the input movie itself
    sim_scores[movie_idx] = -1

    # get top N similar movies
    top_indices = sim_scores.argsort()[::-1][:top_n]

    # create output dataframe
    recommendations_2 = movies.iloc[top_indices][["original_title", "genres"]].copy()
    recommendations_2["similarity_score"] = sim_scores[top_indices]

    return recommendations_2

In [ ]:
recommend_movies_2("Blood & Gold", movies, embedding_matrix, top_n=10)

,original_title,genres,similarity_score
1686,Sisu,"['Action', 'War']",0.537556
8021,Standoff,"['Thriller', 'Drama']",0.482721
7182,Svart krabba,"['Action', 'Thriller']",0.469641
1154,Blood Diamond,"['Drama', 'Thriller', 'Action']",0.445604
9403,Universal Soldier: Day of Reckoning,"['Action', 'Science Fiction', 'Thriller']",0.440959
7023,6 Bullets,"['Thriller', 'Action', 'Crime']",0.436975
6123,Close Range,"['Action', 'Crime', 'Thriller']",0.430763
2104,Woman in Gold,['Drama'],0.419825
3813,Pocahontas,"['Adventure', 'Animation', 'Family', 'Romance']",0.419229
8725,Sentinelle,"['Thriller', 'Action', 'Drama']",0.418337

###6. Create an interactive function for embeddings

In [ ]:
movie_input = input("Enter a movie title: ")

# normalize input: lowercase + remove spaces
normalized_input = movie_input.lower()

results = recommend_movies_2(normalized_input, movies, embedding_matrix, top_n=10)

if isinstance(results, str):
    print(results)
else:
    print(f"\nTop 10 recommendations for '{movie_input}':\n")
results

Enter a movie title: flesh + blood

Top 10 recommendations for 'flesh + blood':

,original_title,genres,similarity_score
6868,The Beastmaster,"['Fantasy', 'Adventure', 'Action']",0.540415
7361,Silent Night,"['Action', 'Thriller', 'Crime']",0.538852
9605,The Head Hunter,"['Horror', 'Fantasy']",0.536768
5357,The Cursed,"['Horror', 'Drama', 'Thriller']",0.514196
8147,Dangerous,"['Action', 'Thriller']",0.500801
9330,Knights of Badassdom,"['Adventure', 'Fantasy', 'Horror', 'Comedy']",0.498712
8677,Little Nicky,"['Comedy', 'Fantasy']",0.496809
7972,Black Death,"['Drama', 'History', 'Horror']",0.494079
8801,Punisher: War Zone,"['Action', 'Crime']",0.493299
8717,The Crow,"['Action', 'Fantasy', 'Horror']",0.491818

### Create a comparison table features for users to decide

In [ ]:
movie_input = input("Enter a movie title: ")

normalized_input = movie_input.lower()

result_1 = recommend_movies_2(normalized_input, movies, embedding_matrix, top_n=10)
result_2 = recommend_movies(normalized_input, df1, similarity_matrix, top_n=10)

if isinstance(result_1, str):
    print(f"Embedding method error: {result_1}")
elif isinstance(result_2, str):
    print(f"TFIDF method error: {result_2}")
else:
    result_1 = result_1.reset_index(drop=True)
    result_2 = result_2.reset_index(drop=True)

    comparison = pd.DataFrame({
        "Embedding Title": result_1["original_title"],
        "Embedding Score": result_1["similarity_score"],
        "TFIDF Title": result_2["original_title"],
        "TFIDF Score": result_2["similarity_score"]
    })

    print(f"\nComparison of Top 10 recommendations for '{movie_input}':\n")
    display(comparison)

Enter a movie title: flesh + blood

Comparison of Top 10 recommendations for 'flesh + blood':

,Embedding Title,Embedding Score,TFIDF Title,TFIDF Score
0,The Beastmaster,0.540415,Nebraska,0.678510
1,Silent Night,0.538852,The Road,0.677514
2,The Head Hunter,0.536768,Walkabout,0.676784
3,The Cursed,0.514196,Life of Pi,0.676010
4,Dangerous,0.500801,Moby Dick,0.675882
5,Knights of Badassdom,0.498712,Дерсу Узала,0.666667
6,Little Nicky,0.496809,Captain Fantastic,0.666667
7,Black Death,0.494079,Io capitano,0.666667
8,Punisher: War Zone,0.493299,Into the Wild,0.666667
9,The Crow,0.491818,El abrazo de la serpiente,0.666667

### Use another model to test distiluse-base-multilingual-cased-v2 to see if can get better result.

In [ ]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model_2 = SentenceTransformer("distiluse-base-multilingual-cased-v2")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

In [ ]:
embedding_matrix_2 = model_2.encode(
    movies["combined_text"].tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/313 [00:00<?, ?it/s]

In [ ]:
def recommend_movies_3(movie_title, movies, embedding_matrix, top_n=10):
    # case-insensitive title matching
    title_to_index = {title.lower(): idx for idx, title in enumerate(movies["original_title"])}

    if movie_title.lower() not in title_to_index:
        return f"Movie title '{movie_title}' not found in the dataset."

    movie_idx = title_to_index[movie_title.lower()]

    # get embedding of selected movie
    movie_vector = embedding_matrix_2[movie_idx].reshape(1, -1)

    # compute cosine similarity
    sim_scores = cosine_similarity(movie_vector, embedding_matrix_2).flatten()

    # exclude the input movie itself
    sim_scores[movie_idx] = -1

    # get top N similar movies
    top_indices = sim_scores.argsort()[::-1][:top_n]

    # create output dataframe
    recommendations_3 = movies.iloc[top_indices][["original_title", "genres"]].copy()
    recommendations_3["similarity_score"] = sim_scores[top_indices]

    return recommendations_3

In [ ]:
recommend_movies_3("Blood & Gold", movies, embedding_matrix, top_n=10)

,original_title,genres,similarity_score
9950,Outcast,"['Action', 'Adventure']",0.575850
1577,Unbroken,"['Drama', 'War']",0.571236
9354,Hellboy,"['Fantasy', 'Horror', 'Action', 'Adventure']",0.566387
1686,Sisu,"['Action', 'War']",0.549719
1141,The Six Triple Eight,"['Drama', 'War', 'History']",0.546573
8185,Austin Powers in Goldmember,"['Comedy', 'Crime', 'Science Fiction']",0.536522
9391,The Other Side of the Door,"['Horror', 'Thriller']",0.535874
5474,Flesh + Blood,"['Adventure', 'Drama']",0.533633
1563,卧虎藏龍,"['Adventure', 'Drama', 'Action', 'Romance']",0.532511
1154,Blood Diamond,"['Drama', 'Thriller', 'Action']",0.530775